stages:
  - test
  - lint

test_job:
  stage: test
  image: python:3.10
  script:
    - pip install poetry
    - poetry install
    - poetry run pytest --cov=src --cov-report=term

lint_job:
  stage: lint
  image: python:3.10
  script:
    - pip install ruff
    - ruff check . --output-format=github
