stages:
  - test
  - lint

test_job:
  stage: test
  image: python:3.10
  script:
    - pip install poetry
    - poetry install
    - poetry run pytest --cov=src --cov-report=term
    - poetry install --with dev
    - poetry run ruff .

lint_job:
  stage: lint
  image: python:3.10
  script:
    - pip install poetry
    - poetry install --with dev
    - poetry run ruff .